[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "btc_1h_regression"
version = "0.1.0"
authors = [{name = "AutoGen"}]
requires-python = ">=3.10"
