symbol: "BTCUSDT"
market: "spot"
timeframe: "1h"
date_range:
  start: "2020-01-01"
  end: "2022-12-31"
paths:
  root: "."
  data_dir: "veriler"
  raw_dir: "veriler/raw"
  processed_dir: "veriler/processed"
  artifacts_dir: "artifacts"
  logs_dir: "artifacts/logs"
  reports_dir: "artifacts/reports"
data_check:
  require_full_coverage: true
  keep_longest_contiguous: true
preprocess:
  tz: "UTC"
  strict_hourly_grid: true
  drop_missing_candles: true
technical_indicators:
  rsi: { period: 14 }
  macd: { fast: 12, slow: 26, signal: 9 }
  ema: [12, 26, 50, 200]
  bb: { period: 20, std: 2.0 }
  stoch: { k: 14, d: 3 }
  atr: { period: 14 }
target:
  type: "next_1h_log_return"
  horizon_hours: 1
split:
  train: 0.70
  val: 0.15
  test: 0.15
  time_series_cv_folds: 0
scaling:
  scaler: "StandardScaler"
train:
  framework: "lightgbm"
  early_stopping_rounds: 200
  n_trials: 5
  timeout_seconds: null
  random_state: 42
  maximize_metric: true
metric:
  primary: "r2"
lstm_baseline:
  enabled: false
  seq_len: 48
  hidden_size: 64
  num_layers: 2
  dropout: 0.2
  lr: 0.001
  batch_size: 256
  epochs: 20
  early_stop_patience: 5
tracking:
  mlflow:
    enabled: true
    experiment_name: "btc_1h_regression"
    tracking_uri: "mlruns"
ui:
  batch_eta_window: 20
  refresh_seconds: 1
